---
# Toy ansible playbook to create a Docker image using only ansible
- name: Setup Docker image build
  hosts: localhost
  connection: local
  tasks:
    - name: docker-builder | Starting the base image in a container
      docker:
        image: "python:2.7-slim"
        command: sleep 36000
        state: started

    - name: docker-builder | Adding container as a host
      add_host:
        name: "{{ item.Name | regex_replace('^/', '') }}"
        groupname: container
        ansible_connection: docker
        ansible_user: root
      with_items: "{{ docker_containers }}"


- name: Provision the container
  hosts: container
  tasks:
    - name: Install the thing
      copy: 
        dest: /entrypoint.py
        content: |
          #!/usr/bin/env python
          print("I'm a Python script")
          print("Wheeeeee!!!!")
        mode: 0755

    # XXX: the final play doesn't execute if there's a failure
    #- command: /bin/false


- name: Finalize the Docker image
  hosts: localhost
  connection: local
  tasks:
    - name: docker-builder | Comitting image
      command: docker commit -c "ENTRYPOINT /entrypoint.py" {{ item }} myimage:1.0
      # stdout is sha256:0000000000...
      with_items: "{{ groups['container'] }}"

    - name: docker-builder | Removing the temp container
      docker:
        name: "{{ item }}"
        image: unused
        state: absent
      with_items: "{{ groups['container'] }}"


# vim:set ts=2 sw=2 expandtab:
